### ISSUE TITLE
Installation in a virtual environment

### ISSUE THREAD

**Issue by jdejoode** [sillsdev/ptx2pdf#442] opened 2021-04-22 08:15 UTC
Thank you for your work on this tool.

I read the installation instructions (for Ubuntu) and I was wondering whether you could add a few notes about installing ptxprint in a virual environment. Right now the system-wide installation installs numpy, for instance, but I'd rather be able to choose specific versions of packages in a virtual environment rather than 'polluting' the system with packages that might have conflicts with other tools on the system.

Could you add installation instructions for running ptx2pdf in a virtual environment?

For instance: 

    mkvirtualenv ptx2pdf
    git clone --depth=1 git@github.com:sillsdev/ptx2pdf.git
    cd ptx2pdf
    pip install -r requirements.txt
    ...

Or alternatively a containerized installation (as a snap, for instance)?

**Comment by jdejoode** [comment] 2021-04-22 08:23
It might be impossible to install in a virtual environment, I'm not sure.

Thanks again for your work on making publishing easier and more accessible.

**Comment by davidg-sil** [comment] 2021-04-22 14:51
My guess is that the issue is the the `pip` command. Is that actually necessary?
 Actually...  where are you getting `requirements.txt` from? I've only ever installed it using manually installed libraries and `python3 ./setup.py`. Does that use pip behind the scenes?

**Comment by jdejoode** [comment] 2021-04-26 13:04
The requirements.txt file is not in the repo, it is the standard name for a file containing python dependencies in a virtual environment. Same for pip.

**Comment by mhosken** [comment] 2021-04-27 04:19
I've just committed an INSTALL.txt and requirements.txt. They are completely untested. All bug reports welcomed. PRs even more welcomed.

**Comment by jdejoode** [comment] 2021-04-28 15:04
Thanks, that is very helpful. Note the spelling mistake requiremets.txt (missing an n) in the main repo. 

Is there a command I could run to test the installation?

**Comment by mhosken** [comment] 2021-05-06 05:23
cd test ; pytest-3 (or whatever pytest works for you with python3) you may have to install pytest. Also I forgot some packages that are needed e.g. xetex might come in handy ;) will update INSTALL.txt to suit.

Oops. I've been sitting on this reply for days. Never hit comment!

**Comment by markpenny** [comment] 2021-05-17 03:52
@jdejoode Just wondering if all is well now on this thread. Can the issue be closed?

**Comment by jdejoode** [comment] 2021-05-17 11:54
Thanks. I've been able to follow the install instructions. I did have to do a few extra steps before running the tests:

- python ./setup.py install
- `pip install pytest` for the testing module to become available in the virtual environment.
- `pip install filelock`

When running `cd test && pytest` I'm getting the following error:

    ModuleNotFoundError: No module named 'regex'

When I run python in my virtualenv, the module regex is available, so it is properly installed

    python
    import regex

**Comment by mhosken** [comment] 2021-05-18 04:02
No ideas this end. All input welcomed.

**Comment by jdejoode** [comment] 2021-05-18 06:57
The packages I have installed in my virtualenv currently are

    $ pip freeze

    appdirs==1.4.4
    attrs==21.2.0
    filelock==3.0.12
    fonttools==4.23.1
    iniconfig==1.1.1
    packaging==20.9
    Pillow==8.2.0
    pluggy==0.13.1
    PTXprint==1.7.1
    py==1.10.0
    pycairo==1.20.0
    PyGObject==3.40.1
    pyparsing==2.4.7
    pytest==6.2.4
    regex==2021.4.4
    toml==0.10.2

This includes a relatively recent version of regex. I'll try downgrading it and report back.

**Comment by jdejoode** [comment] 2021-05-18 07:01
I downgrade to the past four release (based on this list: https://pypi.org/pypi/regex/json), but it does not make a difference. 

The error I'm getting occurs here:

    ptx2pdf/test/../python/scripts/../lib/ptxprint/view.py", line 2, in <module>
        import configparser, os, re, regex, random, collections
    ModuleNotFoundError: No module named 'regex'

**Closed** 2021-08-31 05:20 UTC
Labels: Fixed?
