### ISSUE TITLE
Still not seeing the decoration at end of books

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#215] opened 2020-09-26 01:11 UTC
The correct file name is displayed under the End of Book label on the Diglot+Border page. But we have no idea what path PTXprint thinks it is using. So since it isn't working, I wonder if it just can't find the file or something. Though if I click Select, the file shows up in the listed PDFs in the file browser list. So it should be finding it. 

I wonder if my checking the option of only using illustrations from a certain folder (on the Pictures page) if that might somehow mess up this part of the application. It's weird. As I have never gotten this End of Book decoration to work.

**Comment by mhosken** [comment] 2020-09-28 02:43
Duplicate of #155 and as previously requested, please raise all comments on this issue in that issue. Closed with prejudice.

**Closed by mhosken** 2020-09-28 02:43 UTC
