### ISSUE TITLE
Can't load projects?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#223] opened 2020-09-28 14:07 UTC
With latest version I can't seem to access previously saved project configurations. I still see various configuration folders in the `C:\My Paratext 8 Projects\MIGMA\shared\ptxprint` directory, but in the drop-down for Configuration Name: it just gives me the option of "Default".

Well it seems like that might be fixed by switching to another project and then switching back?

And now I seem to have gotten PTXPrint into a state where it doesn't Print. Click on the Print button and it turns green but immediately turns off. There are no .tex or .log files produced. What gives? I restart PTXPrint - same result. I reinstall PTXPrint - same result. Hmmmm....

**Comment by jeffheath-sil** [comment] 2020-09-28 14:25
Well, I seem to be able to Print again, but don’t know what I did to fix it. I selected several different projects, and different saved configurations, and then it started working again. Kind of scary...

**Comment by davidg-sil** [comment] 2020-09-28 19:39
According to MP in another issue, what you did (change between projects a few times) is the currently known work-around to being able to switch configurations on start-up. The cause of the issue is under investigation, as they say.

**Comment by mhosken** [comment] 2020-09-29 01:54
These transitional conversions are tricky and hard to test. So I wouldn't worry too much that your projects will suddenly stop working for no reason. We know why you had problems, even if we're not sure how to fix it.

**Comment by viverechristus** [comment] 2020-09-29 08:24
I've finally installed 1.1.9, and I too experienced the inability to Print. I did the following, with results as indicated:

1. Open PTXprint, Print (the first Project/Configuration to show up, which is the one I wanted) - nothing
2. Select different Configuration in current project, Print - nothing
3. Cycle through every single configuration in current Project, Print - nothing
4. Change Projects, Print - nothing
5. Select different Configuration in this new Project, Print - nothing
6. Select yet another Project, Print - nothing
7. Close and reopen, Print - SUCCESS

So it appears that the following progression leads to success:

1. Open PTXprint
2. Select a different Project
3. Close
4. Reopen
5. Print (changing to a different project and printing now works, too)

**Comment by viverechristus** [comment] 2020-09-29 08:34
I spoke too soon. I managed to print once, but I still haven't managed to print anything from our primary Project (including my standard configuration).

**Comment by mhosken** [comment] 2020-09-30 03:38
Yes. Very sorry. A nasty path losing bug slipped into the transition code. You should find all the piclist and adjlist files sitting in C:\ if you ran as administrator (or wherever python thinks `/` is). Fixed in 1.1.9.3, I very much hope.

**Comment by viverechristus** [comment] 2020-09-30 03:47
I didn't run as administrator, so no cigar. But no worries, either. Will be happy to have a working copy of PTXprint again soon!

**Comment by viverechristus** [comment] 2020-10-02 08:13
I've got 1.1.9.6 now, and I managed to produce an output for one configuration, but my primary (Matthew-Standard) configuration continues to be unprintable. I click ... nothing. Try changing configurations or projects ... nothing. Try restarting and printing ... nothing.

**Comment by mhosken** [comment] 2020-10-05 03:54
Please create an archive (in ptxprint/advanced tab) and send it to one of us.

**Comment by viverechristus** [comment] 2020-10-06 02:58
In 1.2 it no longer doesn't work. :) Or to put it another way, I can no longer reproduce the problem in 1.2, so consider it resolved! My standard configuration consistently prints.

**Closed** 2020-10-06 03:18 UTC
