### ISSUE TITLE
Turning on Double-column option causes all pictures to disappear 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#140] opened 2020-07-11 17:52 UTC
I usually work with single-column formatted books. But just to try PTXprint out further, I turned on the 2-column option.
I changed nothing else.
Clicked PRINT. The final PDF did not have any pictures in it. 

>> Maybe this has nothing to do with the "double-column" option, but rather because the Layout folder didn't have and Pic List files in it and I had said to use the Pic List files to determine their size and location. If so, this is written up in another issue.<< 

So after I clicked GENERATE and fixed the Pic List files (errors discussed elsewhere), I did get pictures to show! 

I was surprised that the pictures were not confined to the columns. SO I need to read up on this behavior. I had assumed the SPAN settings in the Pic List files were based on the **column width** NOT **page margins width**. 

So I figured that a "0.8" would give me a picture that NEARLY FILLS the **column**. 

But apparently PTXprint sees that as SPAN 0.8 as a % of the **full margin width**, right? Because once I got pictures to show, most went across the whole page regardless of the size, even a picture set to 0.4 (smaller than the column) still cut a swath across the entire page of both columns (looked weird).

Maybe there is another setting for saying "span" refers to "column" or "page" I don't know, but maybe it should. Because this was surprising to me.

Or maybe "**span**" should changed to mean "**% of column width**" (regardless of the number of columns), i.e. 
if set to "**1-column**", the workable space is **page margin width**, 
if set to "**2-columns**", the workable space is set to the space available for **text in a single column**.
But this would disallow pictures to span across both columns...

I'm probably all off-base here! So just say so if I am.

**Comment by markpenny** [comment] 2020-07-12 23:04
@mhosken and @davidg-sil ... I'm not completely following @davidc86 here, but have experimented and found at least one strange bug: In this first PicList I changed the picture in JHN 4:7-8 from col to span and added a *6 to scale it to 60% - and it got completely confused (probably because a 'span' shouldn't have a r/l setting, and it was set as 'tr').
![image](https://user-images.githubusercontent.com/12962708/87258472-e1a6e980-c4f7-11ea-843b-670a48fd44eb.png)

Then I changed the 'tr' to just be 't' and it was a resolved:
![image](https://user-images.githubusercontent.com/12962708/87258510-364a6480-c4f8-11ea-8638-97b721787033.png)

I know that the TeX macros usually ignore the r/l if is a span, or if it is a single col layout. But I'm guessing that the *6 is tripping it up (or making it not see the "span|tr/l". Can this be fixed in the TeX macros please.

**Comment by markpenny** [comment] 2020-07-12 23:51
If I change 'span|b' to include a r/l, like in 10:1 'span|bl' then it also messes up:
![image](https://user-images.githubusercontent.com/12962708/87259380-00f54500-c4ff-11ea-977e-ec4bd33ca3c0.png)

So clearly, we need to tell the macros to ignore the r/l for any span images (regardless of whether they have a scaling factor).

**Comment by davidg-sil** [comment] 2020-07-13 08:04
The macros DO ignore r,l for sg col. So, urn, maybe I broke something.

.

**Comment by davidg-sil** [comment] 2020-07-13 12:20
OK.... I get it now... If you specify span as the size, then a tl/tr can be wider than the column.  This is a regression.  In macros for e.g. ptxprint 0.82  left and right were ignored for span*0.5.

**Comment by davidg-sil** [comment] 2020-07-14 15:35
fix to this issue pushed (earlier today)

**Closed** 2020-07-14 22:15 UTC
