### ISSUE TITLE
Start 1st chapter on a new page

### ISSUE THREAD

**Issue by rlqmadkqk** [sillsdev/ptx2pdf#905] opened 2023-09-06 10:42 UTC
I just typeset 5 books(1&2 Thessalonians, 1&2 Timothy and Titus). Only 1st Thessalonians has chapter 1 on a new page.
[Chepang_Default_1TH-TIT_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/12536446/Chepang_Default_1TH-TIT_ptxp.pdf)

**Comment by mnjames** [comment] 2023-09-07 13:02
It seems highly likely that this is caused by a marker error in the original data. Are you passing all the marker tests inside of Paratext?

In particular, I wonder if there are any non-intro markers (like \p or \m) which occur before \c 1 in those other books.

**Comment by davidg-sil** [comment] 2023-09-15 12:40
If you've still not resolved the issue, please submit an archive to the normal address. -  See the help tab in PTXprint on how to do that.
However, I'd like to recommend taking half an hour to make a mini-project, e.g. based on the first few verses of some out of copyright /  freely distributable USFM version from https://ebible.org/Scriptures/. This  can help demonstrate the problem (and reduce the size of your archive) without causing any copyright/etc problems with your translation team / managers.

**Comment by markpenny** [comment] 2023-10-12 05:16
@rlqmadkqk Is this still an issue? Or did you manage to solve the problem? If so, can we close this open issue?

**Closed** 2023-10-31 01:34 UTC
Labels: info needed
