### ISSUE TITLE
footnote callers not superscript anymore?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#160] opened 2020-08-03 07:00 UTC
With the latest PTXPrint, the footnote callers seem to have reverted to non superscript:
![image](https://user-images.githubusercontent.com/14953913/89154683-3f5eac80-d55f-11ea-863e-cd0f86212436.png)
I would say this is a pretty important issue to resolve...

**Comment by mhosken** [comment] 2020-08-03 11:06
If you are using a \NoteCallerStyle marker reference, then the styling will be taken entirely from that marker and if you don't specify it to \SuperScript then it won't. The fallback styling for callers is the \v marker, which most people \SuperScript. 

Aha you also need to set \NoteCallerRaise to say 6pt (yes it's a true dimension). That could well be the core problem. Likewise \CallerRaise.

**Comment by mhosken** [comment] 2020-08-03 11:18
Digging deeper. You can either use \Superscript on the \NoteCallerStyle and \CallerStyle styles and/or you can use \NoteCallerRaise and \CallerRaise. If you do both, it'll go up a long way since the effects are additive. Note \Superscript reduces the point size of the text, hence the introduction of \CallerRaise, etc. to work around that.

**Comment by markpenny** [comment] 2020-08-03 11:46
Is there a way that we can handle this automatically behind the scenes [on behalf of the users] without expecting them to go in to change their .sty files manually? It was working earlier, so I'd call it a regression...

**Comment by jeffheath-sil** [comment] 2020-08-03 12:10
I did have some leftover stuff in the ptxprint-mods.sty, but when I ripped that out, it's still not giving me superscripted footnote callers. But here's the code that I am using in my outside of PTXPrint XeTeX processing:
# footnotes will use the 'fcaller' style for the caller, smaller text
\Marker f
\CallerStyle fcaller
\FontSize 10

# footnote caller is superscript (even though verse numbers are not)
\Marker fcaller
\Endmarker fcaller*
\StyleType character
\Superscript
\FontSize 9

What are footnote styles **supposed** to look like? (I.e. like standard.) The stuff that is commented out in NestedStyles.sty is very similar to my code above.

**Comment by mhosken** [comment] 2020-08-05 06:07
OK. I see what's going on. My apologies for sending you off on a wild goose chase. I think it's fixed now.

**Comment by jeffheath-sil** [comment] 2020-08-05 07:13
No problem. Geese are my specialty... :-)  Yes, this does seem to be fixed now with the latest macros.

**Closed** 2020-08-07 15:58 UTC
Labels: Fixed?
