### ISSUE TITLE
Diglot issue - primary text repeats leaving huge gaps

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#532] opened 2021-10-05 02:00 UTC
There seems to have been a regression in diglot handling somewhere shortly after 1.9.2 was released. The issue is that huge chunks of the Primary text are getting repeated (with NOTHING showing in the Secondary text) so big areas of white space are observed.
![2021-10-01 20_30_36-](https://user-images.githubusercontent.com/12962708/135948443-8abf0066-8b83-4e18-a417-bff44c51be16.png)

**Comment by davidg-sil** [comment] 2021-10-05 08:31
Can you confirm that this is actually in the TeX macros please.  I've seen a bad merges recently that gave repeated text, making this a python issue, not XeTeX.
Confirmation comes from looking for (in example given) `\c 5` in the final merged usfm file. (a total of 2 '\c 5's would mean the problem is with XeTeX macros, but if there are more `\c 5` then the  number of columns, that's a python issue.)

**Comment by mhosken** [comment] 2021-10-05 08:40
I did check the usfmerge output and there was no duplication. That was my first thought too.

**Comment by davidg-sil** [comment] 2021-10-05 10:02
Interesting... I've just found a merging error that while different to the above, it's definitely a merging error. But it doesn't actually repeat the chapter number. Like the example above, there's no chapter number on the 2ndary text, because the primary has stolen it. Thus chapter numbers are not the things to search for, instead pick a unique section of repeated text.

**Closed** 2021-10-07 07:55 UTC
Labels: priority, diglot, bug, Fixed?, Python
