### ISSUE TITLE
Request: option to turn off (full) justification of footnote text

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#66] opened 2020-05-19 08:31 UTC
For Scripture Text, there is an option to turn on or off "Justify text". However, it appears that for Footnotes, there is no such option - if the footnotes are printed as paragraphs, they are automatically justified. Is it possible to add an option to turn this off (or is there a trick to do it without a UI option)?

By the way, PTXprint is working wonderfully! We're preparing Matthew for a church check and making lovely draft copies using PTXprint. Thank you.

**Comment by mhosken** [comment] 2020-05-19 10:02
You should be able to set \Justification to left, right, center for the f Marker (or whatever note you called \ParagraphedNotes with). Mind you the macros don't allow much rag (2em max) Do we want to make that adjustable? The normal paragraph rag is 1/4 column width.

**Comment by viverechristus** [comment] 2020-05-20 07:38
In PrintDraft-mods.sty I tried these lines:

```
\Marker f
\Fontsize 9
\Justification Left

\Marker x
\Fontsize 9
\Justification Left
```

I'm still getting full-justified notes. See here:

![image](https://user-images.githubusercontent.com/915182/82418684-7d434d00-9aa7-11ea-8f88-4d5c09e08a77.png)

I'm guessing that in TeX there's some sort of paragraph wrapper, and the justification is being assigned to that. What think you?

**Comment by viverechristus** [comment] 2020-05-20 07:45
On the other hand, maybe I'm wrong, since a few pages later I get this. Clearly ragged right. (But why does notes t and u start on a new line?)

![image](https://user-images.githubusercontent.com/915182/82419011-fd69b280-9aa7-11ea-8316-97a474a72b9e.png)

**Comment by mhosken** [comment] 2020-05-20 10:15
Notes of different classes are not merged into the same paragraph. There is some help with that with ptxprint, but we may need to do better. I have a user experience question.

If we add something to the .sty file like: 

```
\Marker t
\Notegroup f
```
Would you want t to get it's styling from f or to have its own styling and just be merged into the same collection of notes as f?

**Comment by davidc86** [comment] 2020-05-20 18:04
This is strange. I thought tweaking the justification on Marker f and Marker x would make a difference. But I just ran my text with "\Justification Left" on the 'f' marker, and it made NO DIFFERENCT: 

![image](https://user-images.githubusercontent.com/65363206/82481003-a57c7d00-9aa2-11ea-93c6-13906ac839d4.png)

So, that is worth tweaking the behavior so PTXprint supports ragged edges if someone turns off justification for \f.

**Comment by mhosken** [comment] 2020-05-21 06:26
I know you won't believe me, but the references are being set ragged right. The problem is that the right rag is set to 2em (which you can just see above if you look at it hard) and then justification is used for the rest of the space. I have changed it so that the list line in a paragraph has a full fill from the right, which should sort this out.

**Comment by markpenny** [comment] 2020-05-22 18:16
We are now setting these as \Justification Left by default. If a user wants them justified, then they can override that in PrintDraft-mods.sty (I think). But @mhosken how can this be done? Because I don't see a **\Justification Full** anywhere. I only see **Left**, **Right** and **Center**.

**Comment by mhosken** [comment] 2020-05-23 05:01
The ptx macros don't care what you put into the \Justification marker, it can even be blank. Anything other than "left", "right", "center" will be interpretted as full justification and the other values as per what they say. And yes case is important so not "Left".

**Comment by markpenny** [comment] 2020-05-23 06:32
Yes, I've just changed "Left" > "left" and am closing this issue.

**Closed by markpenny** 2020-05-23 06:32 UTC
Labels: priority
