### ISSUE TITLE
v1.2.9.7 "Always start 1st Chapter on new page"

### ISSUE THREAD

**Issue by listentwice** [sillsdev/ptx2pdf#268] opened 2020-10-23 10:30 UTC
v1.2.9.7 "Always start 1st Chapter on new page" only worked on the first book in the PDF, not the subsequent books.
Thanks

**Comment by markpenny** [comment] 2020-10-31 10:24
Is it possible that you have BOTH of these settings turned on? If so, that could be the cause. I just tried it with only the 1st option selected, and it worked as expected (v 1.3). But when I turned on the second option, it (understandably) ignored the previous setting.
![image](https://user-images.githubusercontent.com/12962708/97776785-171f3200-1bd0-11eb-9f90-a69c382fe30c.png)
I'm wondering if I should make those two mutually exclusive...

**Comment by mabacon** [comment] 2020-11-02 05:37
![Screen Shot 2020-11-02 at 11 17 12](https://user-images.githubusercontent.com/34570767/97833428-6dd65a00-1cfd-11eb-9c3f-2d8789cbf4cf.jpg)
![Screen Shot 2020-11-02 at 11 19 56](https://user-images.githubusercontent.com/34570767/97833438-72027780-1cfd-11eb-8cd7-25224894ac4c.jpg)
![Screen Shot 2020-11-02 at 11 20 05](https://user-images.githubusercontent.com/34570767/97833442-76c72b80-1cfd-11eb-983f-1d0d33984c3b.jpg)
![Screen Shot 2020-11-02 at 11 20 15](https://user-images.githubusercontent.com/34570767/97833454-7cbd0c80-1cfd-11eb-97e7-635590b2492b.jpg)

Retested with 1.3
I am expecting book intro on one page, and Chapter 1 to be forced to the next page.
That happens in Gen (1st book), but not Luke (2nd book) in this test.

**Comment by markpenny** [comment] 2020-11-02 06:33
Okay, very strange indeed. Could you "Create ZIP Archive" and
      send me a link to the ZIP file. Hopefully that will shed some
      light on WHY is isn't doing what it should.
    Mark
    
    On 11/2/2020 6:37 PM, Mike B wrote:
    
    
      
      
        
        
        
      Retested with 1.3
        I am expecting book intro on one page, and Chapter 1 to be
        forced to the next page.
        That happens in Gen (1st book), but not Luke (2nd book) in this
        test.
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/268#issuecomment-720247354",
"url": "https://github.com/sillsdev/ptx2pdf/issues/268#issuecomment-720247354",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
ɦuuəd ʞɹɐw ● Language Technology Senior Consultant ● South Asia Group ● SIL International  ● Based in NZ

**Comment by markpenny** [comment] 2020-11-02 22:01
@davidg-sil Would you have any idea on why this \\pagebreak is being ignored?
![image](https://user-images.githubusercontent.com/12962708/97923956-c2440d00-1dc3-11eb-9208-3215a554d74a.png)
I've tried this in other projects and it works fine - but there's something strange going on here, for sure. I can forward the .zip file if that is helpful for debugging.

**Comment by davidg-sil** [comment] 2020-11-03 20:53
Hmm. Just looking in the code, the value of ```\ifendbooknoeject``` (which I guess is one of those toggles above) is set to true, then all manual (and book end) ```\pagebreak``` commands get ignored at present. 
I'll fix that.

**Comment by davidg-sil** [comment] 2020-11-03 21:07
MP, I don't think they ought to be  mutually exclusive. One puts book intros on a different page to chapter 1, the other starts a new book (intro) on a new page.
Of course, eventually someone will want book intros on even numbered pages and book starts on odd-numbered ones, or something. At which point they'll try to say:
```
\ifodd\pageno\pagebreak\fi
```
or some other collection of cryptic runes, and then they'll be confused why it won't work properly all the time. The answer will be because TeX reads ahead and works out such things as it read them...
I guess there's a chance that it might work straight after a page break. I'm not sure.

**Comment by markpenny** [comment] 2020-11-03 21:57
@davidg-sil davi Glad to read that these can continue to be independent of each other. And yes, the fix works. So I'm closing the issue. @listentwice (nice name!) It will be available in 1.3.1 (which might get released later today).

**Closed by markpenny** 2020-11-03 21:57 UTC
Labels: Fixed?

**Comment by listentwice** [comment] 2020-11-04 11:42
Fixed
