### ISSUE TITLE
Option "Exclusively use selected folder" breaks the PRINT process 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#90] opened 2020-05-25 17:26 UTC
In PT9, the \fig field is this:  

\fig Nus o hnu ti lasmyer Palestinake|alt="The cities and towns in the land of Palestina" src="Holy Land BW-Selaru.tif" size="col" ref="8:40"\fig* 

The picture is definitely in the local\figures folder. PT9 sees it and displays it. But PTXprint 0.7.0 now fails to find it. (I selected the "only look in this folder") The error displayed is this: 

![image](https://user-images.githubusercontent.com/65363206/82833290-9b37f580-9e8b-11ea-9ced-3d2aadcd7cac.png)

The file PTXprint is looking for is: /tmpPics/Holy_Land_BW-Selaru.tif

The specific warning: 
!Unable to load picture or PDF file
Check if image/PFD file is available on the system

Makes me think the problem is with spaces, as the actual filename is "Holy Land BW-Selaru.tif"

**Comment by davidc86** [comment] 2020-05-25 17:44
WELL, THAT wasn't the problem. I renamed the file with _ and reconnected it with the \fig field. It still fails. So I reverted those back to spaces.

UNCHECKING the "Exclusively use selected folder" allows the process to run successfully. Bummer. As I'm seeing that the TIF maps are being displayed pixelated rather than in the high-quality resolution of the original TIFs in the "selected folder". 

It'd be good if we could keep the hi-res versions of these maps in the PDF.

**Comment by markpenny** [comment] 2020-05-28 05:09
@davidc86 Thanks for this report. We've been busy working on the aligned diglot, so haven't done much on fixing issues in the last few days. To help me figure what might be happening, could you open the file containing this image:
\fig Nus o hnu ti lasmyer Palestinake|alt="The cities and towns in the land of Palestina" src="Holy Land BW-Selaru.tif" size="col" ref="8:40"\fig*
and send me the REAL text which Paratext is "masking" when presented within PT itself. If the project is still USFM2 then it actually stores the fig definition like this: 
\fig |co00604b.tif|span|||bagavantal kalit ropo samdo gaḍi kītor|1:23\fig*
I'm guessing that there's something we're missing, but maybe it is just buggy code related to the "exclusively use this folder" option that was just introduced. Thanks.

**Comment by davidc86** [comment] 2020-05-29 18:03
It is the very last bit of text in Act 8:40:
...
\p
\v 38 Lemade iry Etiopia desike yaso ma wasi kereta desike kimres, ode rorw ei benbenuke kralake, ma Filipus byabtis a i.
\v 39 Ode kyoat rabetik toha benbenu desy, kyala mait bonyo Hulasokwe Memeanke kyor Filipus ba, ma lema imin. Ma iry Etiopia desike lema myatakit a i de. Lemade syaur wasi laklakutke bai lulkwe, ode imukmuka imarmara i.
\p
\v 40 Klala kyala mait huruk bonyo Filipus imin o a nus Asdodke de. Lemade byetik toha nus desy, ode lyakut a lyola nusare ode hnuare ma yabrita Brit Eraske, ma ti kyait a nus Kaisareake. \fig The cities and towns in the land of Palestina|Holy Land BW-Selaru.tif|col|||Nus o hnu ti lasmyer Palestinake|8:40\fig*
\c 9
...
I don't know if the fact that it's a \fig field at the end of a chapter? But PTXprint doesn't seem to mind this field when the "exclusive folder" is NOT checked. If you want the whole Acts USFM file, I can attach it.

**Comment by markpenny** [comment] 2020-05-31 12:50
@davidc86 Hi again, I've done my best to reproduce this issue - even copying the string into my own test project to see if I can work out why it isn't showing up - but I can't get the same (failing) result. I'm wondering if there is a misunderstanding due to the wording in the tooltip:
![image](https://user-images.githubusercontent.com/12962708/83352622-713e7180-a36a-11ea-8db7-04ff0bf6db7e.png)

Or perhaps some other setting/reason that is preventing the image from showing up. For example, is the image too large to fit on the page (vertically) and therefore "dropping off the end". If so, try scaling it in the PicList |col*.5| should work...

I'm assuming that if it is a TIF, then it gets converted to a PDF before being displayed, and you can confirm that that is what is happening by turning on "Only use empty placeholders":
![image](https://user-images.githubusercontent.com/12962708/83352649-aa76e180-a36a-11ea-80c0-70226da6607b.png)
The only other thing I wonder about is whether you have something strange in the "Order of preferred image types" option.
![image](https://user-images.githubusercontent.com/12962708/83352696-16f1e080-a36b-11ea-9497-d9c9da4cb8d8.png)

BTW - if you remove JPG from that list, then it should always look for TIFs/PDFs and PNGs and not give you any low-resolution images.

If none of these solve the issue - get back to me, but I'll probably have to take a look using Zoom or Skype.

**Comment by davidc86** [comment] 2020-06-02 16:09
Here is a screen shot of my Pictures page:

![image](https://user-images.githubusercontent.com/65363206/83542664-4454a080-a4c9-11ea-9a08-a46f39cd91ad.png)

This is AFTER the crash. So it now shows the "missing" pictures -- which aren't missing, but PTXprint thinks they are.

And I confirmed that the Selected folder was ...\local\figures which contains all the high-res pictures used in the project.

You did say that it converts TIF to PDF, right? So that means nearly every picture file is converted to PDF, but it doesn't explain why only the maps are causing grief. 

NOTE that I also reordered the Image types, so JPG is at the end, not that this helped any.

**Comment by davidc86** [comment] 2020-06-02 16:12
So, I removed "JPG" from the Image type list. And I unchecked the "Exclusively use selected folder" option. BUT, I still got the following error message:

![image](https://user-images.githubusercontent.com/65363206/83543305-381d1300-a4ca-11ea-9100-0995414a3586.png)

So, I'm still scratching my head on this one.

**Comment by markpenny** [comment] 2020-06-02 18:09
Hi @davidc86 - I've finally been able to reproduce this (in 0.7.0) - which is a relief. There is certainly something strange going on - as I was able to put any other image (with the same name as your image) in that location and it displayed as expected. I tried all kinds of combinations of BW and resolutions, but never managed to get my (MapCreator) file to show up. In the end I had an idea to scale the image, and then it showed up.

So it looks to me like we're not automatically scaling it to fit the page - and so it (sometimes) leaves a big gap where it should be, but never actually places the image.

Here's a workaround - which I'd like you to try:
In the PicList, after the "col" or "span" add a manual scaling factor of *.7 and see if the image shows up. Something like this:
    ACT 8.40 |mapSelaru.tif|span*.7|tl||Nus o hnu ti lasmyer Palestinake|8:40

In 0.7.1 we will automatically scale images to *.5 the size (when generating the piclist) IF we detect that it is a single-column publication. This will at least ensure that they show up; and then they can be increased in size if needed. We probably also need some better logic to scale them to FIT (either vertically, or horizontally).

I'm curious to find out what happens with your current setup if you (temporarily) change to 2-col layout... does the map show up?

And, yes, you should always be able to use the highest resolution files, as seen here from my zoomed in sample:
![image](https://user-images.githubusercontent.com/12962708/83554153-f1f79c00-a529-11ea-8e27-a862f46b0d3c.png)

**Comment by davidc86** [comment] 2020-06-02 19:52
Okay, I've been looking into this some more, and weirdly, the **tmpPics** folder is failing to generate the PDFs for 6 of my TIF files. AND it RENAMES the PDF files it creates from nearly all the other TIF files in the SFM. For example: 
a filename: HK00150B.TIF 
becomes:    hk00150.pdf

So, PTXprint is making it lowercase and DELETING the final 'B' in the name. (How does it know this is a safe thing to do?)

As for the missing pictures, here are the ones I know are not being made into PDFs:
   Holy_Land_BW-Selaru.tif
   Paul1-BW_Selaru.tif
   Paul2-BW_Selaru.tif
   Paul3-BW_Selaru.tif
   Paul4-BW_Selaru.tif
   Peta_Lokasi_Paulus_5T_BW_Selaru.tif

BUT, this is what PTXprint reports as missing:

Missing Pictures:
Peta_Lokasi_Paulus_5T_BW_Selaru, Paul1-BW_Selaru, Holy_Land_BW-Selaru, Paul2-BW_Selaru, Paul3-BW_Selaru, Paul4-BW_Selaru

I've even tried shortening the name, e.g. "Peta_Lokasi_Paulus_5T_BW_Selaru.tif" to "PetaLokasi5T.tif" but it made no difference. These 6 files refuse to be made into PDFs. So PTXprint falls back onto the JPG version of these. And so if I eliminate JPG from the possible list of image types, PTXprint fails.

These TIF files seem okay to me, and while they are kind of large >1MB <2MB they are not as large as the map for Jonah (>3MB) -- which converts into a PDF just fine (nice resolution!).

Any ideas would be much appreciated.

**Comment by davidc86** [comment] 2020-06-03 01:43
QUESTION before I try that you say 0.7.1 will make them all scaled to *5. But what happens if I already have carefully defined all the pictures in the books' PicLists. Do they get written over?

**Comment by davidc86** [comment] 2020-06-03 01:51
Here is the problem. It isn't that the picture don't show in the PDF. They DO show. BUT they DON'T show using the high-res TIF version of those 6 pictures. The final PDF is generated using the JPG versions of these 6 files. If I turn off JPG, then PTXprint bombs, because there is no TIF->PDF file generated for these 6 files. 

So, I am suspecting the "bug" is NOT with the "exclusive folder" option. But rather for some reason the TIF to PDF conversion does not work for those 6 files. So if I limit the folder to just the TIF folder, and the picture process doesn't generate PDFs for those TIF files in the tmpPics folder, then PTXprint bombs (because files are missing). But if I turn OFF the "Exclusive" folder, then PTXprint finds the missing files in the JPG folder and copies those to tmpPics folder and uses those.

**Comment by davidc86** [comment] 2020-06-03 01:52
Do you want copies of the 6 TIF files?
Maybe there is something about them that your conversion tool doesn't like.

**Comment by davidc86** [comment] 2020-06-03 02:21
Okay! I verified that the problem is with those files not converting to PDF. I opened the TIFs and saved them as JPG (and kept those large JPGs in the same folder as the TIFs). And then I selected the "Exclusively use" option and PTXprint ran just fine, and all the maps are in hi-res. SO, this "Exclusively use" issue is not a bug with the "exclusively use" option, RATHER this is a problem with why the converter wouldn't convert the maps. Do TIF files have to be in black and white? I think this might be in a gray scale... just wondering out loud.

**Comment by markpenny** [comment] 2020-06-03 04:54
> QUESTION before I try that you say 0.7.1 will make them all scaled to *5. But what happens if I already have carefully defined all the pictures in the books' PicLists. Do they get written over?

No, we won't override what you have specified in a PicList. It is only at the point of 1st creating a PicList that PTXprint will "helpfully" change "col" to "span*.5" for single column publications AND diglots. (If you already had "span", it will keep those as "span" and not shrink them.) 

And of course you can then remove the *.5 if you want them full size, or change the value to whatever suits you.

So if you would prefer that this DOESN'T happen, then just create your PicList when in 2-column mode, and it won't affect them at all. :-)    Now, where is all this going to be documented... ??

**Comment by markpenny** [comment] 2020-06-03 04:56
> Do you want copies of the 6 TIF files?
> Maybe there is something about them that your conversion tool doesn't like.

Yes, that would be helpful for further testing... Are they generated from MapCreator? Because I am aware that there are some strange things in those image files too - and maybe they are causing the TIF>PDF converter to fail.

**Comment by markpenny** [comment] 2020-06-03 04:58
> Okay! I verified that the problem is with those files not converting to PDF. I opened the TIFs and saved them as JPG (and kept those large JPGs in the same folder as the TIFs). And then I selected the "Exclusively use" option and PTXprint ran just fine, and all the maps are in hi-res. SO, this "Exclusively use" issue is not a bug with the "exclusively use" option, RATHER this is a problem with why the converter wouldn't convert the maps. Do TIF files have to be in black and white? I think this might be in a gray scale... just wondering out loud.

Thanks for verifying this. I'll do some more digging to work out why that is. Hopefully there is an answer somewhere...

**Comment by davidc86** [comment] 2020-06-03 12:48
Here is the Holy Land TIF pic. I think it is actually in "color" (like the gray sea is actually a tan).

[Holy_Land_BW-Selaru.zip](https://github.com/sillsdev/ptx2pdf/files/4723365/Holy_Land_BW-Selaru.zip)

I had to zip it because github won't allow TIF files to be uploaded directly.

**Comment by markpenny** [comment] 2020-06-04 04:44
Excellent - now we have something to work with, and I'm getting a warning which tells me how to fix it too:
WARNING:root:Image contains transparency which cannot be retained in PDF.
WARNING:root:img2pdf will not perform a lossy operation.
WARNING:root:You can remove the alpha channel using imagemagick:
WARNING:root:  $ **convert input.png -background white -alpha remove -alpha off output.png**

I'll try adding those options and see if it behaves better. And while testing I also came across some anomalies in the way that the "Order of preferred image types" is [not] working.

Thanks for your persistence in helping us get this right... It will be worth it in the end.

**Comment by markpenny** [comment] 2020-06-05 12:31
@davidc86 Thanks for your persistence... Okay! Now after 2 days of working on it, we have a system that strips out the alpha-channel from images and also checks the proportions of the image to see if it will fit on the page. If not, it automatically pads the sides with white background so that the image will fit vertically on the page (and not run off the page and disappear completely - which is what _was_ happening to some images).
I'm hoping you can test this out for us (I'll send you a link privately) before we release it more widely - as a LOT has changed and we no longer use the TIF>PDF route, but rather TIF>JPG (but still keeping the images at a high resolution).
![image](https://user-images.githubusercontent.com/12962708/83876347-5ac35c00-a756-11ea-814a-3e0c7ae6ce1c.png)
[PS. Please excuse the mashup of my text with your map!]

**Comment by davidc86** [comment] 2020-06-05 18:51
AH! Okay Great. That explains a LOT.
Yes, this new strategy works. And I see where all the TIFs are converted to Hi-Res JPG. Nice. Thank you.
The only bug I’m seeing now is PTXprint losing track of where the PicList is being stored. (It seems to start out with it in …shared\PTXprint\PicList\ folder but if we use a Configuration file, it saves the PicList into that configurations folder. (Good), but then it loses track of which set of files it should use. So it EDITS in the PTXprint\PicList folder and USES the Configuration’s PicList folder to format the output! So edits are ignored.

I suspect that is not a major bug, just really confusing at first.
David

**Comment by markpenny** [comment] 2020-06-06 09:21
I'm closing this issue now and will focus on solving #102 to make sure we pick up the right PicList when there are multiple sets hanging around!
I appreciate your diligence in testing and giving really quality/specific feedback each time. :-)

**Closed by markpenny** 2020-06-06 09:21 UTC
