### ISSUE TITLE
Last line (book) in the Table of Contents table is missing its page number

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#175] opened 2020-08-12 03:51 UTC
Here is the bit of ours:
![image](https://user-images.githubusercontent.com/65363206/89973189-bebe4100-dc2d-11ea-8511-d93708987f88.png)

Also note that the column for the long name is not wide enough. (The page has plenty of room to make the table wider.)
Nor have I figured out how to get the wrapped text to not be vertically spaced so far away, so wrapped lines are tighter than new lines; nor how to get it to  hang indent a bit more, so it is clearly a wrapped text line, rather than a new line.

**Comment by markpenny** [comment] 2020-08-12 06:25
I'm not sure how to replicate this... ...as it appears to work fine.
![image](https://user-images.githubusercontent.com/12962708/89982060-1f4e8c00-dcc9-11ea-806e-0b30e40c0f63.png)
Does this happen for all projects, and regardless of which book is last?

**Comment by davidc86** [comment] 2020-08-12 12:17
No it doesn't matter which book it is. And it only started going this in 0.9.0 + 
I have tried it will different number of books and each time the last one is missing the number.
NOTE: I am using TOC1 and TOC3 (not TOC2) for my output table. Not sure if that makes any difference.

**Comment by mhosken** [comment] 2020-09-25 04:45
Could you re-test this in 1.1.9 and if it fails send a zip archive for local testing. TIA.

**Comment by davidc86** [comment] 2020-09-26 00:17
Just tested it and it is still a glitch in v1.1.9. Sorry. Here is a screen shot: 

![image](https://user-images.githubusercontent.com/65363206/94325341-f7ab3e80-ff6b-11ea-85ee-232536c0100d.png)

Note that the last line for "Peta" (Maps) does not have a page number. (And wrapping of long names is less than elegant too. Just an FYI on that.)

**Comment by mhosken** [comment] 2020-09-28 03:23
You did part 1 of the above request. What about part 2? Please send an archive if you want to see any movement on this issue.

**Comment by davidc86** [comment] 2020-10-23 02:03
I have sent an archive some time ago, and I have done Part 1.
Did you guys get the archive? If not where do you want it? It is too large to email.
Also, as I said and showed in #259, the same thing happens when printing a single book.
Am I the only one seeing this?

**Comment by markpenny** [comment] 2020-10-26 08:43
@davidc86 Can you confirm whether this has finally been resolved in 1.3? I've got the files you've sent, so if it is still an issue, I'll take a look later this week.

**Comment by markpenny** [comment] 2020-11-02 09:40
@davidg-sil I can confirm that I'm also seeing the same behaviour with the test data that was sent. However, the .toc file **has** the correct information in there:
```
\tr \tc1 Ksala Tabaca Kitab Lanke\tc2 Ksala\tcr3 562
\tr \tc1 Indeks Bertopikke\tc2 Topik\tcr3 567
\tr \tc1 Tbaca Kitab Lanke ti ainke krala ne\tc2 Tbaca\tcr3 572
\tr \tc1 Gambar o Peta-nare\tc2 Peta\tcr3 584

```
so I'm not sure where/how it is dropping that last page number (584).

**Comment by mhosken** [comment] 2020-11-03 02:52
I wonder if the problem is that the table is implicitly closed by the end of file rather than the start of another paragraph style. Some things to try:
- insert `\p` after the table
- move the call to `\endt@ble` in `\ptxfile` in ptx-stylesheet.tex up 2 lines to before the `\ifhmode` test.

**Comment by davidc86** [comment] 2020-11-03 04:32
I'm sorry I have not had time to research this more closely (we are doing a Consultant check of Mark), but  I did notice that if I don't include my own custom styles or maybe it is the PTXprint styles file, without those styles, PTXprint will format the table of contents just fine (with larger fonts). So I suspect it might be some style setting that is causing a change in behavior.

But if I don't explicitly specifying those TOC styles this also affects our "Read through the Bible" table at the back of the book (which needs very small fonts). So, that's a problem: if I don't specify styles, the TOC works. If I specify the styles so the Read through the Bible looks correct, then the TOC doesn't work (loses the last page number). 

Personally I'd like the table of contents to NOT use the standard table styles, so they'd be different from other tables (since they are front matter anyway). It would also be helpful if there was some special table style I could specify uniquely for the Read Through the Bible tables since they have their own specific formatting needs. 

Maybe I'll have time later this week to look at it more deeply.

**Comment by davidg-sil** [comment] 2020-11-03 11:46
location-specific stylig will be possible using ```\esb```...```\esbe``` to aplpy a   category, (if you don't want page breaks) or  (EVENTUALLY)  with usfm milestones, even without any change in markers.

**Comment by mhosken** [comment] 2020-11-03 13:01
I was thinking milestones.

**Comment by davidg-sil** [comment] 2020-11-03 21:23
Agreed. Because milestones are intentionally non-heirarchical, and without
any presupposed 'it all fits on one page' semantics, I think they're the
right way to go.

I've just noticed that the USFM code seems to say that if a given
milestone-defined region is started with sid="123", it only ends with
eid="123". I wish they'd just kept to id= on both...

**Closed** 2020-12-03 06:07 UTC
Labels: Fixed?
