### ISSUE TITLE
Include Back Matter PDF(s) no longer working

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#120] opened 2020-06-24 08:13 UTC
using 0.8.5 - 

I can no longer include a Back Matter PDF. The job outputs to PDF, but the selected Back Matter PDF is not included in the final output.

I tried with only a single book (Mat) and with both Mat and Glo, but results were the same. Including or not including pictures makes no difference. 

I've confirmed that the PDF exists and is not corrupted. In previous versions I've included it no problem. (I reselected the PDF a couple times, as well, just to be sure the path is correct.)

(But lots of other stuff is working great, and the new features and fixes are much appreciated. For now I can attach an extra PDF using another piece of software.)

**Comment by markpenny** [comment] 2020-06-24 08:23
Thanks for reporting it. I'll look into it later today and hopefully find the source of the regression...

**Comment by markpenny** [comment] 2020-06-24 17:09
@viverechristus  I've now tried this in 0.8.4 and 0.8.5 and it still seems to be working fine for me. Could you please check again and confirm that it still doesn't work after re-starting PTXprint. and if it is still broken please send me the last few lines of the .tex file which should look something like this:

```
%%%%% Front Matter PDF file(s) get included here %%%%%
\includepdf{C:/My Paratext 9 Projects/WSGlatin/PrintDraft/frontExample.pdf}
...etc..
%%%%% Back Matter PDF file(s) get included here %%%%%
\includepdf{C:/My Paratext 9 Projects/WSGlatin/PrintDraft/backExample.pdf}

```
Are there any signs of a missing PDF file in the .log file? I'm clutching at straws to shed some more light on this...

**Comment by viverechristus** [comment] 2020-06-25 06:18
If I include the file as BOTH front matter AND as back matter, it correctly places it in both places (I used the same file for convenience, and it shows up at the front and the back of the generated PDF).

![image](https://user-images.githubusercontent.com/915182/85666145-4f74a800-b6e6-11ea-893a-2041dbe77c48.png)

```
%%%%% Front Matter PDF file(s) get included here %%%%%
\includepdf{C:/Users/Josh/Desktop/JaraiBooks.pdf}

%\GenerateTOC[]{ptxprint-MATJraKhmr.toc}
%\BodyColumns=1     % Temporarily set this to Single Column for the ToC page(s)
%\ptxfile{ptxprint-MATJraKhmr.toc}
%\BodyColumns=2     % But ensure it goes back to the chosen Single/Double setting for the main body text

%%%%% Load Paratext USFM %%%%%
\XeTeXdefaultencoding "utf-8"
\def\closeadjlist{\relax}
\def\closepiclist{\relax}
% job files:
\catcode`\%=12
\PtxFilePath={C:/My Paratext 8 Projects/JraKhmr/PrintDraft/}
\ptxfile{41MATJraKhmr-draft.SFM}
\catcode`\%=14

%%%%% Back Matter PDF file(s) get included here %%%%%
\includepdf{C:/Users/Josh/Desktop/JaraiBooks.pdf}

\end
```

However, if I ONLY select Include Back Matter (the selfsame PDF!), it doesn't show up at all:

![image](https://user-images.githubusercontent.com/915182/85666004-23f1bd80-b6e6-11ea-9a9e-a850b824267e.png)

```
%%%%% Front Matter PDF file(s) get included here %%%%%


%\GenerateTOC[]{ptxprint-MATJraKhmr.toc}
%\BodyColumns=1     % Temporarily set this to Single Column for the ToC page(s)
%\ptxfile{ptxprint-MATJraKhmr.toc}
%\BodyColumns=2     % But ensure it goes back to the chosen Single/Double setting for the main body text

%%%%% Load Paratext USFM %%%%%
\XeTeXdefaultencoding "utf-8"
\def\closeadjlist{\relax}
\def\closepiclist{\relax}
% job files:
\catcode`\%=12
\PtxFilePath={C:/My Paratext 8 Projects/JraKhmr/PrintDraft/}
\ptxfile{41MATJraKhmr-draft.SFM}
\catcode`\%=14

%%%%% Back Matter PDF file(s) get included here %%%%%


\end
```

Auger that!

**Comment by markpenny** [comment] 2020-06-25 08:00
Thanks @viverechristus  - those two screenshots helped me get straight to the issue, which has now been fixed. It will be in the next release (0.8.6 or later).

**Closed by markpenny** 2020-06-25 08:00 UTC

**Comment by viverechristus** [comment] 2020-06-26 08:34
Confirmed - this now works for me in 0.8.6
