### ISSUE TITLE
Table of Contents feature fails to add the page number for the last entry (regardless of the number) 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#259] opened 2020-10-22 20:31 UTC
I just happen to run the Single Book process for Genesis (Kejadian         Kej.) And this is the table of contents it produced: 

![image](https://user-images.githubusercontent.com/65363206/96926746-fba38100-1483-11eb-9f6c-b63de301654b.png)

Notice there is no page number at the end of the line. I suspect if I did 2 books, the first one would get a page number but the second one would not.

So it is not a function of the number of books, or that fact the last book that has been showing this was a Maps section in the "BAK" book. But rather it is the LAST book in the list won't get a page number.

Note: not sure if it matters, but I am including a PDF for Front Matter in these test.

**Comment by mhosken** [comment] 2020-10-23 01:54
This is a duplicate of #175 for which there is a request for data outstanding.

**Closed by mhosken** 2020-10-23 01:54 UTC
