### ISSUE TITLE
Copyright info "does its own thing"

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#272] opened 2020-10-24 20:06 UTC
I entered the copyright info into each fig spec in the piclist (in the ptxprint gui), according to the format wanted by SIL PNG literacy dept. 

But in the colophon what is printed for each fig is the abbreviation that I placed long ago in the PT \fig statements, except for the HK and LB pics, which contain full (c) and date info but in a different statement format than what I want. What is especially confusing is that, while ptxprint was open my "correct" copyright lines appeared in the View > Piclist > Edit Details tab for each fig, but I can't see these "correct" lines in any of the piclist files that are currently in the RTTT folder. 

When I closed and reopened ptxprint, now the View > Piclist > Edit Details tab is back to the default size/position and blank copyright fields for all the pics.

What is even stranger is that my MAT pics, for each of which I unsuccessfully tried to specify a copyright statement into the piclist, still appear in the colophon with the abbreviated statements from my PT MAT file. But the ACT pics, which do have similar abbrev. in the copyright field in my ACT PT file, do not appear at all in the colophon. So ptxprint seems to be recognizing that I entered copyright info for the MAT pics but not for the ACT ones; but it is ignoring what I entered and reverting to the PT fig statements.

**Comment by markpenny** [comment] 2020-11-17 02:51
@KimB2017 I think this should be resolved in ver 1.4 which should be out in the next few days. Please note that if you use any of the images with these prefixes: cn|co|hk|lb|bk|ba|dy|gt|dh|mh|mn|wa|dn|ib then the copyright statement will turn up according to what is in SIL's typesetting manual. It is only if the image isn't recognized as being from the list above that you can have your own statement. Perhaps we should disable/hide the copyright statement option for all the above image sets.
Please let us know if the issue is fixed once you get hold of 1.4

**Comment by mhosken** [comment] 2021-01-15 03:10
Assume this is resolved given no response.

**Closed by mhosken** 2021-01-15 03:10 UTC
Labels: Fixed?
